---
title: "GenAI vs Academic Skills Development"
bibliography: references.bib
author:
  - name: John Wilson
    email: jwilso3@ed.ac.uk
    affiliation: Edinburgh Medical School, University of Edinburgh

keywords:
  - example
---

This article originally appeared as a [post on the Unversity of Edinburgh blog Teaching Matters](https://blogs.ed.ac.uk/teaching-matters/genai-vs-academic-skills-development/) in February 2025.

## Introduction

Back in September 2024, an "Angry Developer" posted their opinion on the effect of AI code tools (see [Why Copilot is making programmers worse at programming](https://www.darrenhorrocks.co.uk/why-copilot-making-programmers-worse-at-programming/)).

This got me thinking about the effect of AI LLM tools on _academic skills_.
Hopefully in way the gives some useful perspective on why-or-when _not_ to turn to AI, beyond the "because the uni said 'No!'" rules, and that might resonate with our students on a more personal level.

## Erosion of Academic Skills

Just as AI can cause programmers to lose their deep understanding of coding principles, it can also cause us to lose other essential academic skills.
An important reason for this is that LLMs have __no knowledge of their own!__.
They _literally_ make stuff up [@hicks2024chatgpt].
E.g., relying too heavily on AI to write reports will have an impact on your own development of critical reasoning and writing skills.
If your works are mostly written by AI, it will affect how you learn to structure arguments and use evidence to effectively support your narrative.
As a marker, one of the things that really stands out about AI generated work is the "voice".
By relying on AI, you not only remove your voice form the content, but lose the opportunity of ever even developing your own voice.
As an example, after writing this, I asked an LLM to re-write one (and only one) of the following paragraphs.
See if you can spot which one has a different voice.


## Reduced Practical Learning

In programming, we never get our code right first time, and our feedback comes in the form of error messages.
In our own studies, engaging directly with material is essential for "deep learning" (pun not _really_ intended, but I'll take it).
For example, if you use routinely use AI to quickly summarize articles or generate lab reports, you will find it more difficult to develop a whole chain of skills.
  
![Over-reliance on AI tools is ikely to weaken key academic skills, which once weakened, will lead to a cyle of continued skills impoverishment.
(Totally based on opinion - I got no refs for this)](/chapters/images/C44_ai-vs-ac.png){#fig-diagram fig-alt="A sequence of academic skills pointing from 'Meaningful Engagement', 'Developing Critical Thinking', 'Extracting Personal Insights', 'Forming Hypotheses Independently', and then to 'Creating Original Conclusions'.
An arrow loops back from 'Creating Original Conclusions' to 'Meaningful Engagement', labeled 'Reinforced weakening of academic skills'."}

And most importantly, if the work is mostly AI generated, the feedback you receive does not apply to you personally at all.
So it's worthless!


## Dependence on AI for Solutions

AI generated code often results is code that is...  just...  a bit...  _odd_!
And that's assuming the code even works.
So, when programmers use AI to generate code, they might not fully understand the solutions provided.
There is a parallel here in academic settings where you might use AI to complete assignments without fully engaging with the underlying concepts.
I think it should be self-evident that copy-pasting a generated response does nothing to help you as an academic, but it filters beyond just the academic context.
Imagine a situation where you were asked a question _identical_ to a Uni exam...
in a _job interview_...

## Narrowed Creative Thinking

AI tools can definitely be an efficient way to complete a task, but they might also limit your own creative thinking.
In your academic work, you might miss out on the creative process of developing unique (think "novel") ideas and solutions.
Yes, AI might sometimes suggest a promising idea, but it really does not have any clue about the topic.
And with an over-reliance on AI for our work, neither do we.
For example, using AI to brainstorm essay questions or projects can prevent you from broth conceiving and exploring your own interesting ideas.
Again, if it helps, think in terms of "novelty", often a requirement for publishing.

## Bias & lived experience

AI models are trained on vast datasets from the internet, reflecting the "most common" values and perspectives, often dominated by only a few societal groups.
This can lead to reinforcement of their viewpoints while under representing diverse experiences, especially those from minority groups.

Relying heavily on AI for ideas might dilute your unique lived experience, regardless of your background.
Remember, AI lacks personal insights and creativity.
Ensure your voice is evident in your work, as this is what distinguishes it from the work of others.
Critically assess AI-generated content, particularly when you have unique perspectives to share - these are the moments when your individuality really matters.
AI is undoubtedly a useful tool, but let your individuality shine in your work to avoid creating yet another indistinguishable AI-generated piece.


## Balancing AI Use

While AI can be a powerful tool to enhance learning and productivity, it's important for you to use it as a supplement rather than a replacement for your own efforts.
Encouraging a balanced approach can help maintain and even enhance your critical thinking skills.
For example, you can use AI to check your work or, perhaps, generate ideas, but make sure to engage deeply with the material and develop your own understanding and solutions.
If you need any further convincing, ask yourself if you have ever felt "imposter syndrome".
Then, ask if the confidence with which AI speaks actually increases your own confidence in your own knowledge...


AI tools like Copilot certainly offer significant benefits, but what we need to impress upon students is that using these tools has a real effect on development of vital academic skills.
Even using for the widely "accepted" use cases, e.g. "idea generation", is problematic.
If ideas-generation or direction-finding are delegated to AI, students risk becoming invisible in their own work, their work risks disappearing from the wider literature landscape, and, ultimately, they end up doing the bidding of our robot overlords.


::: {.content-visible when-format="html" unless-format="epub"}

## References {.unnumbered}

:::